[serial]
device: /dev/ttyUSB0

[prometheus]
hostname: 127.0.0.1
port: 8888


[mqtt]
hostname: 192.168.1.206
port: 1883
username: mqtt_user
password: password
keepalive: 60

reconnect_initial: 1
reconnect_max: 60
reconnect_jitter: 20
